# To create a replicaset and to maintain pods with that

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-01
  labels: #label for replicaset
    app: nginx
    #setting pod deletion cost
  annotations:
    controller.kubernetes.io/pod-deletion-cost: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx #has to match the label of the pod described below. this is how pods are identified and determination happens on which rs a pod belongs to. so, label needs to be unique
  template:
    metadata:
      labels:
        app: nginx #label for pod
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.20
---

apiVersion: v1
kind: Pod
metadata:
  name: rs-01-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginx

## Always maintain unique labels.
