apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
      - name: CATALOGUE_HOST
        value: "hello from catalogue"

---
#defining a config map to pass the values

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-07
data:
  CATALOGUE_HOST: "catalogue"
  CART_HOST: "cart"

---
#creating a pod by obtaining specific values from config map

apiVersion: v1
kind: Pod
metadata:
  name: pod-07-cm
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
      - name: CATALOGUE_HOST
        #obtaining specific value from config map using valuefrom
        valueFrom:
          configMapKeyRef:
            name: cm-07 #config map name
            key: CATALOGUE_HOST
      - name: CART_HOST
        #obtaining specific value from config map using valuefrom
        valueFrom:
          configMapKeyRef:
            name: cm-07 #config map name
            key: CART_HOST

---

#creating a pod by obtaining all values from config map
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-cm-1
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      #envfrom is used to obtain all values from config map
      envFrom:
      - configMapRef:
          name: cm-07

---
#creating a config file

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-07-file
#service file info being passed with data parameter
data:
  catalogue.service: |
    [Unit]
    Description = Catalogue Service

    [Service]
    User=roboshop
    Environment=MONGO={{ secrets.MONGO }}
    Environment=MONGO_URL="{{ secrets.MONGO_URL }}"
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=catalogue

    [Install]
    WantedBy=multi-user.target

  cart.service: |
    [Unit]
    Description = Cart Service

    [Service]
    User=roboshop
    Environment=MONGO={{ secrets.MONGO }}
    Environment=MONGO_URL="{{ secrets.MONGO_URL }}"
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=cart

    [Install]
    WantedBy=multi-user.target

---
#mounting a config file (file created in previous section)
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-cm-2
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config #being mounted to /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: cm-07-file #file created in the previous section

---
#secrets - key/value can be defined or secrets file can be mounted
#refer https://kubernetes.io/docs/concepts/configuration/secret/ for example on how secrets can be mounted
#creating a file for secrets
apiVersion: v1
kind: Secret
metadata:
  name: secret-07-1
data:
  password: YWJjZEAxMjM0
#secrets need to be provided in base64 format
---
#providing secrets info directly as mentioned in the above section is not desirable. referencing the secret file created above using secretkeyref
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-secret
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
      - name: password
        valueFrom:
          secretKeyRef:
            name: secret-07-1
            key: password
