#https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    security: S1
spec:
  containers:
  - name: nginx
    image: nginx
#  nodeName: ip-192-168-84-247.ec2.internal
  tolerations:
  - key: "appTypes"
    operator: "Exists"
    effect: "NoSchedule"
