#https://medium.com/@kadimasam/kubernetes-storage-pv-pvc-and-storage-class-c107eba9c232
#https://kubernetes.io/docs/concepts/storage/persistent-volumes/

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-pod
spec:
  containers:
    - name: nginx
      image: nginx  # Use your desired image
      volumeMounts:
        - mountPath: /usr/share/nginx/html  # Path inside the container where the volume will be mounted
          name: my-pvc-storage
  volumes:
    - name: my-pvc-storage
      persistentVolumeClaim:
        claimName: ebs-pvc


